version: '3.8'

services:
  my-home-next:
    container_name: my-home-next
    image: node:14-alpine
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: /bin/sh -c "yarn install && yarn build && yarn start"
